<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<groupId>com.example.demo</groupId>
	<artifactId>parent</artifactId>
	<packaging>pom</packaging>
	<version>${revision}</version>

	<modules>
		<module>dto</module>
		<module>properties</module>
		<module>data</module>
		<module>service</module>
		<module>api</module>
		<module>app</module>
	</modules>

	<name />
	<description />
	<url />
	<licenses>
		<license />
	</licenses>
	<developers>
		<developer />
	</developers>
	<scm>
		<connection />
		<developerConnection />
		<tag />
		<url />
	</scm>

	<properties>
		<java.version>25</java.version>
		<revision>1.0.0-SNAPSHOT</revision>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.microsoft.sqlserver</groupId>
				<artifactId>mssql-jdbc</artifactId>
				<version>13.4.0.jre11</version>
				<scope>runtime</scope>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>api</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>app</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>properties</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>dto</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>data</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>service</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<!-- All modules inherit these dependencies -->
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.5.0</version>
				</plugin>

				<plugin>
					<groupId>io.github.git-commit-id</groupId>
					<artifactId>git-commit-id-maven-plugin</artifactId>
					<version>10.0.0</version>
				</plugin>

				<plugin>
					<groupId>cz.habarta.typescript-generator</groupId>
					<artifactId>typescript-generator-maven-plugin</artifactId>
					<version>4.1.1</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
		</plugins>
	</build>

</project>